# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('up_date', models.DateTimeField(verbose_name='date published')),
                ('time_source', models.DateTimeField(null=True)),
                ('timestamp_source', models.IntegerField(null=True)),
                ('content', models.TextField(blank=True)),
                ('keyword', models.CharField(max_length=300)),
                ('head', models.CharField(blank=True, max_length=300)),
                ('thumb_img', models.CharField(blank=True, max_length=150)),
                ('viewoneday', models.IntegerField(default=0)),
                ('viewweek', models.IntegerField(default=0)),
                ('viewmonth', models.IntegerField(default=0)),
                ('views_all', models.IntegerField(default=0)),
                ('userupload', models.CharField(choices=[('0', 'AdminAuto'), ('1', 'SuperAdmin'), ('2', 'Mod'), ('3', 'User')], max_length=2)),
            ],
            options={
                'verbose_name': 'Spaper Content',
            },
        ),
        migrations.CreateModel(
            name='NameNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'News Name',
            },
        ),
        migrations.CreateModel(
            name='RssLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_rss', models.CharField(blank=True, max_length=100)),
                ('tag_header', models.CharField(blank=True, max_length=100)),
                ('type_header', models.CharField(blank=True, max_length=100)),
                ('name_header', models.CharField(blank=True, max_length=100)),
                ('tag_content', models.CharField(blank=True, max_length=100)),
                ('type_content', models.CharField(blank=True, max_length=100)),
                ('name_content', models.CharField(blank=True, max_length=100)),
                ('tag_keyword', models.CharField(blank=True, max_length=100)),
                ('type_keyword', models.CharField(blank=True, max_length=100)),
                ('name_keyword', models.CharField(blank=True, max_length=100)),
                ('namenew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NameNews')),
            ],
            options={
                'verbose_name': 'Rss Links',
            },
        ),
        migrations.CreateModel(
            name='TypesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typenews', models.TextField()),
            ],
            options={
                'verbose_name': 'Types News',
            },
        ),
        migrations.AddField(
            model_name='rsslinks',
            name='typenew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TypesNews'),
        ),
        migrations.AddField(
            model_name='content',
            name='name_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NameNews'),
        ),
        migrations.AddField(
            model_name='content',
            name='type_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TypesNews'),
        ),
    ]
