# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='keyword',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
