# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170719_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='yes_short',
            field=models.BooleanField(default=False),
        ),
    ]
