# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_content_yes_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsslinks',
            old_name='namenew',
            new_name='name_new',
        ),
        migrations.RenameField(
            model_name='rsslinks',
            old_name='typenew',
            new_name='type_new',
        ),
    ]
